# database would be created to the postgre\
development:
  adapter: postgresql
  encoding: unicode
  database: Gist_Blog_development
  pool: 5
  host: localhost
  username: postgres
  password: password
 socket: /var/run/postgresql/.s.PGSQL.5432 

test:
  adapter: postgresql
  encoding: unicode
  database: Gist_blog_test
  pool: 5
  username: postgres
  password: password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
